# Generated by Django 4.2.11 on 2024-05-02 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AISubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.aicategory')),
            ],
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Letter_document', models.FileField(blank=True, null=True, upload_to='CL_Documents/')),
                ('upload_date', models.DateField(auto_now_add=True, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_CoverLetter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoverLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CL_template_Pdf', models.FileField(blank=True, null=True, upload_to='CL_Template/Pdf/')),
                ('CL_template_Word', models.FileField(blank=True, null=True, upload_to='CL_Template/Word')),
                ('IsPaid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModelChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CV_template_Pdf', models.FileField(blank=True, null=True, upload_to='CV_Template/Pdf/')),
                ('CV_template_Word', models.FileField(blank=True, null=True, upload_to='CV_Template/Word/')),
                ('IsPaid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('userId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_resume', models.TextField(blank=True, null=True)),
                ('latest_goal', models.TextField()),
                ('latest_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_temperature', models.FloatField(blank=True, null=True)),
                ('maximum_temperature', models.FloatField(blank=True, null=True)),
                ('default_temperature', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_temperatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_choice', models.FloatField(default=0.5)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='null', max_length=500, null=True)),
                ('company_name', models.CharField(blank=True, default='null', max_length=500, null=True)),
                ('programing_language', models.CharField(blank=True, default='null', max_length=500, null=True)),
                ('location', models.CharField(blank=True, default='null', max_length=500, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Set_Goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CV_document', models.FileField(blank=True, null=True, upload_to='CV_Documents/')),
                ('upload_date', models.DateField(auto_now_add=True, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_CV', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProPilotLauncher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.coverletter')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.setgoals')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.resumecv')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pro_Pilot_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaxToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeMockInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterviewTime', models.DateTimeField(blank=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.setgoals')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FreeMockInterviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlashCardInterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default='null', max_length=500, null=True)),
                ('answer', models.TextField(blank=True, default='null', max_length=1000, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.aicategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.aisubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AiProPilotLauncher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.coverletter')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.setgoals')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.resumecv')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ai_Pro_Pilot_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiInterviewProPilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterviewTime', models.DateTimeField(blank=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.setgoals')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AiInterviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiCodingMathsProPilotLauncher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_goal', models.TextField(blank=True, null=True)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.coverletter')),
                ('programing_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.setgoals')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.resumecv')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AiCodingMaths_Pro_Pilot_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiCodingMaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsActive', models.BooleanField(default=True)),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.setgoals')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ai_Coding_Maths', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('model_name', models.ForeignKey(default='llama2-70b-4096', on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.modelchoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'model_name')},
            },
        ),
    ]
